services:
#    ninfac_conta.example:
#        class: Ninfac\ContaBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    ninfac_conta.admin.ctl_empresa:
        class: Ninfac\ContaBundle\Admin\CtlEmpresaAdmin
        arguments: [~, Ninfac\ContaBundle\Entity\CtlEmpresa, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: CtlEmpresa }
